name = "Iosevka Nerd Font"
extends = "base"

[custom]

[custom.mono]
font = "Iosevka Nerd Font"
weight = "Medium"
bold = "Heavy"
italic = "Oblique"
bold_italic = "Heavy Oblique"
size = 14

[custom.kitty]
font = "Iosevka"
append = "Nerd Font Complete"
