name = "base"

[colors.terminal]
bg = "#000000"
fg = "#ffffff"

color0 = "#080808"
color1 = "#B21818"
color2 = "#18B218"
color3 = "#B26818"
color4 = "#1818B2"
color5 = "#B218B2"
color6 = "#18B2B2"
color7 = "#B2B2B2"
color8 = "#686868"
color9 = "#FF5454"
color10 = "#54FF54"
color11 = "#FFFF54"
color12 = "#5454FF"
color13 = "#FF54FF"
color14 = "#54FFFF"
color15 = "#FFFFFF"

[colors.base16]
base00 = "#181818"
base01 = "#282828"
base02 = "#383838"
base03 = "#585858"
base04 = "#b8b8b8"
base05 = "#d8d8d8"
base06 = "#e8e8e8"
base07 = "#f8f8f8"
base08 = "#ab4642"
base09 = "#dc9656"
base0A = "#f7ca88"
base0B = "#a1b56c"
base0C = "#86c1b9"
base0D = "#7cafc2"
base0E = "#ba8baf"
base0F = "#a16946"

[custom]
vim_colorscheme = "vim.cmd('colorscheme base16-default-dark')"
emacs_colorscheme = "doom-one"
