name = "Dracula"
extends = "base"

[colors.terminal]
bg = "#282A36"
fg = "#E6E6E6"

color0 =  "#000000"
color1 =  "#FF5555"
color2 =  "#50FA7B"
color3 =  "#F1FA8C"
color4 =  "#BD93F9"
color5 =  "#FF79C6"
color6 =  "#8BE9FD"
color7 =  "#BFBFBF"
color8 =  "#4D4D4D"
color9 =  "#FF6E67"
color10 = "#5AF78E"
color11 = "#F4F99D"
color12 = "#CAA9FA"
color13 = "#FF92D0"
color14 = "#9AEDFE"
color15 = "#E6E6E6"

[colors.base16]
base00 = "#282936"
base01 = "#3a3c4e"
base02 = "#4d4f68"
base03 = "#626483"
base04 = "#62d6e8"
base05 = "#e9e9f4"
base06 = "#f1f2f8"
base07 = "#f7f7fb"
base08 = "#ea51b2"
base09 = "#b45bcf"
base0A = "#ebff87"
base0B = "#00f769"
base0C = "#a1efe4"
base0D = "#62d6e8"
base0E = "#b45bcf"
base0F = "#00f769"

[custom]
vim_colorscheme = "vim.cmd('colorscheme base16-dracula')"
emacs_colorscheme = "doom-dracula"
