name = "OneDark"
extends = "base"

[colors.terminal]
bg = "#282C34"
fg = "#ABB2BF"

color0 = "#5C6370"
color1 = "#E06C75"
color2 = "#98C379"
color3 = "#E5C07B"
color4 = "#61AFEF"
color5 = "#C678DD"
color6 = "#56B6C2"
color7 = "#ABB2BF"
color8 = "#4C566A"
color9 = "#BE5046"
color10 = "#98C379"
color11 = "#D19A66"
color12 = "#61AFEF"
color13 = "#C678DD"
color14 = "#56B6C2"
color15 = "#3E4452"

[colors.base16]
base00 = "#282c34"
base01 = "#353b45"
base02 = "#3e4451"
base03 = "#545862"
base04 = "#565c64"
base05 = "#abb2bf"
base06 = "#b6bdca"
base07 = "#c8ccd4"
base08 = "#e06c75"
base09 = "#d19a66"
base0A = "#e5c07b"
base0B = "#98c379"
base0C = "#56b6c2"
base0D = "#61afef"
base0E = "#c678dd"
base0F = "#be5046"

[custom]
# vim_colorscheme = "vim.cmd('colorscheme base16-onedark')"
vim_colorscheme = "require('colorbuddy').colorscheme('onebuddy')"
vim_lualine_theme = "onedark"
emacs_colorscheme = "doom-one"
