name = "Tokyo Night"
extends = "base"

[colors.base16]
base00 = "#24283b"
base01 = "#1f2335"
base02 = "#292e42"
base03 = "#565f89"
base04 = "#a9b1d6"
base05 = "#c0caf5"
base06 = "#c0caf5"
base07 = "#c0caf5"
base08 = "#f7768e"
base09 = "#ff9e64"
base0A = "#e0af68"
base0B = "#9ece6a"
base0C = "#1abc9c"
base0D = "#41a6b5"
base0E = "#bb9af7"
base0F = "#ff007c"

[colors.terminal]
bg = "#1a1b26"
fg = "#c0caf5"

color0 = "#15161E"
color1 = "#f7768e"
color2 = "#9ece6a"
color3 = "#e0af68"
color4 = "#7aa2f7"
color5 = "#bb9af7"
color6 = "#7dcfff"
color7 = "#a9b1d6"
color8  = "#414868"
color9  = "#f7768e"
color10 = "#9ece6a"
color11 = "#e0af68"
color12 = "#7aa2f7"
color13 = "#bb9af7"
color14 = "#7dcfff"
color15 = "#c0caf5"

[custom]
vim_colorscheme = "vim.g.tokyonight_style = 'night'\nvim.cmd('colorscheme tokyonight')"
vim_lualine_theme = "tokyonight"
