name = "Base with japanese themed Polybar"
extends = "base"

[custom.polybar]
modules_left = "i3"
modules_center = "time "
modules_right = "cpu memory xkeyboard date"
text_offset = "2"
icon_font_scale ="8"
antialias = "true"
bottom = "false"
height = "32"
i3_label = "%icon%"
cpu_icon = "CPU:"
ram_icon = "RAM:"
layout_icon = "KB:"
ws0_icon = "一"
ws1_icon = "二"
ws2_icon = "三"
ws3_icon = "四"
ws4_icon = "五"
ws5_icon = "六"
ws6_icon = "七"
ws7_icon = "八"
ws8_icon = "九"
ws9_icon = "十"
ws_icon = "〇" # default
